/**
 * Profile + schedule fetch helpers (Track C — Phase II.6).
 *
 * The OpenAPI spec is regenerated by `make docs`; until that lands the
 * profile + schedule endpoints are typed locally so the UI can compile
 * + ship before the backend deploy. Once the spec ships, callers can
 * migrate to the generated `api` client without changing the React
 * surface.
 */

export type ScheduleFrequency = 'once_daily' | 'twice_daily' | 'disabled';
export type ThemePreference = 'system' | 'light' | 'dark';

export interface UserProfile {
  readonly display_name: string | null;
  readonly email_aliases: readonly string[];
  readonly redaction_aliases: readonly string[];
  readonly presidio_enabled: boolean;
  readonly theme_preference: ThemePreference;
  readonly schedule_frequency: ScheduleFrequency;
  readonly schedule_times_local: readonly string[];
  readonly schedule_timezone: string;
}

export interface UserSchedule {
  readonly schedule_frequency: ScheduleFrequency;
  readonly schedule_times_local: readonly string[];
  readonly schedule_timezone: string;
  readonly next_run_at_utc: string | null;
}

export interface UserProfilePatch {
  readonly display_name?: string | null;
  readonly email_aliases?: readonly string[];
  readonly redaction_aliases?: readonly string[];
  readonly presidio_enabled?: boolean;
  readonly theme_preference?: ThemePreference;
}

export interface UserSchedulePatch {
  readonly schedule_frequency?: ScheduleFrequency;
  readonly schedule_times_local?: readonly string[];
  readonly schedule_timezone?: string;
}

const CSRF_HEADER = 'X-CSRF-Token';
const CSRF_COOKIE = 'briefed_csrf';

/**
 * Read the CSRF cookie value, if present.
 *
 * @returns The token string or `null`.
 */
function readCsrfCookie(): string | null {
  const entries = document.cookie.split('; ');
  for (const entry of entries) {
    const [key, ...rest] = entry.split('=');
    if (key === CSRF_COOKIE) return decodeURIComponent(rest.join('='));
  }
  return null;
}

/**
 * Issue an authenticated JSON request, throwing on non-2xx.
 *
 * @param url - Absolute or relative URL.
 * @param init - Standard fetch options.
 * @returns The parsed JSON body.
 */
async function jsonFetch<T>(url: string, init: RequestInit = {}): Promise<T> {
  const headers = new Headers(init.headers ?? {});
  headers.set('Accept', 'application/json');
  if (init.body !== undefined && !headers.has('Content-Type')) {
    headers.set('Content-Type', 'application/json');
  }
  const method = (init.method ?? 'GET').toUpperCase();
  if (method !== 'GET' && method !== 'HEAD') {
    const csrf = readCsrfCookie();
    if (csrf) headers.set(CSRF_HEADER, csrf);
  }
  const response = await fetch(url, { ...init, credentials: 'same-origin', headers });
  if (!response.ok) {
    throw new Error(`Profile API request failed (${response.status})`);
  }
  return (await response.json()) as T;
}

/** GET /api/v1/profile/me */
export function fetchProfile(): Promise<UserProfile> {
  return jsonFetch<UserProfile>('/api/v1/profile/me');
}

/** PATCH /api/v1/profile/me */
export function patchProfile(body: UserProfilePatch): Promise<UserProfile> {
  return jsonFetch<UserProfile>('/api/v1/profile/me', {
    method: 'PATCH',
    body: JSON.stringify(body),
  });
}

/** GET /api/v1/profile/me/schedule */
export function fetchSchedule(): Promise<UserSchedule> {
  return jsonFetch<UserSchedule>('/api/v1/profile/me/schedule');
}

/** PATCH /api/v1/profile/me/schedule */
export function patchSchedule(body: UserSchedulePatch): Promise<UserSchedule> {
  return jsonFetch<UserSchedule>('/api/v1/profile/me/schedule', {
    method: 'PATCH',
    body: JSON.stringify(body),
  });
}
